name: cordex-examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cmor>=3.8.0
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - cf_xarray
  - cftime
  - flox
  - netCDF4
  - xesmf
  - cfchecker
  - compliance-checker
  - cdo
  - python-cdo
  - jupyter-book
  - intake-esm
  - ghp-import
  - fsspec
  - requests
  - aiohttp
  - pint
  - py-cordex
  #- pip:
  #  - git+https://github.com/euro-cordex/py-cordex.git # always use master for now
